# Generated by Django 5.2.3 on 2025-06-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_app', '0003_alter_category_icon_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nom_app.category'),
        ),
    ]
